name 'kibana'
maintainer 'Niels Krijger'
maintainer_email 'niels@kryger.nl'
license 'Apache 2.0'
description 'Installs/Configures nginx'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.0.1'
depends 'ark', '>= 0.2.4'
depends 'nginx'
depends 'elasticsearch'